// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BackTop: typeof import('./src/components/content/back-top/back-top.vue')['default']
    MainTabbar: typeof import('./src/components/content/main-tabbar/main-tabbar.vue')['default']
    Navbar: typeof import('./src/components/common/navbar/navbar.vue')['default']
    Scroll: typeof import('./src/components/common/scroll/scroll.vue')['default']
    Tabbar: typeof import('./src/components/common/tabbar/src/tabbar.vue')['default']
    TabbarItem: typeof import('./src/components/common/tabbar/src/tabbar-item.vue')['default']
    VanActionBar: typeof import('vant/es')['ActionBar']
    VanActionBarButton: typeof import('vant/es')['ActionBarButton']
    VanActionBarIcon: typeof import('vant/es')['ActionBarIcon']
    VanSearch: typeof import('vant/es')['Search']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
  }
}

export { }
