// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    MainTabbar: typeof import('./src/components/content/main-tabbar/main-tabbar.vue')['default']
    Tabbar: typeof import('./src/components/common/tabbar/src/tabbar.vue')['default']
    TabbarItem: typeof import('./src/components/common/tabbar/src/tabbar-item.vue')['default']
  }
}

export { }
